export const SEARCH_DOMAIN_START = 'SEARCH_DOMAIN_START'
export const SEARCH_DOMAIN_SUCCESS = 'SEARCH_DOMAIN_SUCCESS'
export const SEARCH_DOMAIN_ERROR = 'SEARCH_DOMAIN_ERROR'

export const CART_ADD = 'CART_ADD'
export const CART_REMOVE = 'CART_REMOVE'
export const CART_SAVE = 'CART_SAVE'